const PAGE_A11Y_TITLES={dashboard:'BEASTMODE dashboard',workout:'Gym and workout tracking',meals:'Nutrition and meals',progress:'Progress tracking',habits:'Habit tracking',bmi:'Body profile and settings'};
const DIALOG_FOCUSABLE='button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])';
const dialogOrigins=new WeakMap();
let dialogTitleIndex=0;
function ensurePageHeading(id){const page=document.getElementById(`page-${id}`);if(!page)return;let heading=page.querySelector('h1');if(!heading){heading=document.createElement('h1');heading.className='sr-only';heading.textContent=PAGE_A11Y_TITLES[id]||id;page.prepend(heading)}if(!heading.id)heading.id=`page-${id}-title`;page.setAttribute('aria-labelledby',heading.id)}
function wrapPageRenderer(name,id){const original=window[name];if(typeof original!=='function')return;window[name]=function(...args){const result=original.apply(this,args);ensurePageHeading(id);return result}}
Object.entries({rDash:'dashboard',rWork:'workout',rMeals:'meals',rProg:'progress',rHabits:'habits',rBMI:'bmi'}).forEach(([name,id])=>wrapPageRenderer(name,id));
function dialogFocusable(modal){return[...modal.querySelectorAll(DIALOG_FOCUSABLE)].filter(item=>!item.hidden&&item.getAttribute('aria-hidden')!=='true')}
function restoreDialogFocus(modal){const origin=dialogOrigins.get(modal);dialogOrigins.delete(modal);requestAnimationFrame(()=>{if(origin?.isConnected)origin.focus()})}
function closeAccessibleDialog(modal){if(!modal)return;modal.remove();restoreDialogFocus(modal)}
function trapDialogFocus(event,modal){if(event.key==='Escape'&&!modal.classList.contains('pin-lock')){event.preventDefault();closeAccessibleDialog(modal);return}if(event.key!=='Tab')return;const items=dialogFocusable(modal);if(!items.length){event.preventDefault();modal.focus();return}const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
function enhanceDialog(modal){if(!(modal instanceof HTMLElement)||modal.dataset.accessibleDialog==='true')return;modal.dataset.accessibleDialog='true';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.tabIndex=-1;const title=modal.querySelector('.modal-title,.pin-title');if(title){if(!title.id)title.id=`dialog-title-${++dialogTitleIndex}`;modal.setAttribute('aria-labelledby',title.id)}else modal.setAttribute('aria-label',modal.classList.contains('pin-lock')?'App locked':'Dialog');dialogOrigins.set(modal,document.activeElement);modal.addEventListener('keydown',event=>trapDialogFocus(event,modal));requestAnimationFrame(()=>{const first=dialogFocusable(modal)[0];(first||modal).focus()})}
const accessibilityObserver=new MutationObserver(records=>records.forEach(record=>{record.addedNodes.forEach(node=>{if(!(node instanceof HTMLElement))return;if(node.matches('.modal-overlay,.pin-lock'))enhanceDialog(node);node.querySelectorAll?.('.modal-overlay,.pin-lock').forEach(enhanceDialog)});record.removedNodes.forEach(node=>{if(node instanceof HTMLElement&&dialogOrigins.has(node))restoreDialogFocus(node)})}));
accessibilityObserver.observe(document.body,{childList:true,subtree:true});
