function recentDateKeys(days=7){return Array.from({length:days},(_,index)=>{const date=nowGMT4();date.setUTCDate(date.getUTCDate()-(days-1-index));return date.toISOString().slice(0,10)})}
function workoutPersonalRecords(){
  const records={};for(const log of S.workoutLogs||[])for(const exercise of log.exercises||[])for(const set of exercise.sets||[])if(set.done&&Number(set.weight)>Number(records[exercise.name]?.weight||0))records[exercise.name]={weight:Number(set.weight),reps:Number(set.reps)||0,date:log.date};
  return Object.entries(records).sort((a,b)=>b[1].weight-a[1].weight);
}
function barChart(values,color,formatter=value=>Math.round(value).toLocaleString()){
  const max=Math.max(...values.map(item=>Number(item.value)||0),1);
  return`<div class="metric-chart">${values.map(item=>`<div class="metric-col" title="${h(item.label)}: ${h(formatter(item.value))}"><div class="metric-value">${h(formatter(item.value))}</div><div class="metric-bar-wrap"><div class="metric-bar" style="height:${Math.max(3,Math.round((Number(item.value)||0)/max*100))}%;background:${color}"></div></div><div class="metric-label">${h(item.short||item.label)}</div></div>`).join('')}</div>`;
}
function renderInsights(){
  const target=document.getElementById('page-dashboard');if(!target)return;
  const dates=recentDateKeys(),logs=(S.workoutLogs||[]).filter(log=>dates.includes(log.date)),nutrition=dates.map(date=>({date,...(S.dailyNutrition[date]||{})})),nutritionDays=nutrition.filter(day=>day.updatedAt||day.kcal),avgKcal=nutritionDays.length?Math.round(nutritionDays.reduce((sum,day)=>sum+(Number(day.kcal)||0),0)/nutritionDays.length):0,avgProtein=nutritionDays.length?Math.round(nutritionDays.reduce((sum,day)=>sum+(Number(day.p)||0),0)/nutritionDays.length):0,volume=logs.reduce((sum,log)=>sum+(Number(log.volume)||0),0),habitDone=Object.values(S.habits||{}).filter(Boolean).length,habitTotal=Math.max(1,(S.habitNames||[]).length*7),weights=S.progress.map(item=>Number(item.weight)).filter(Boolean),weightChange=weights.length>1?weights.at(-1)-weights[0]:null,records=workoutPersonalRecords();
  const volumeByDate=dates.map(date=>({label:date,short:date.slice(5),value:convertedVolume(logs.filter(log=>log.date===date).reduce((sum,log)=>sum+(Number(log.volume)||0),0))})),calorieBars=nutrition.map(day=>({label:day.date,short:day.date.slice(5),value:Number(day.kcal)||0})),weightBars=S.progress.map((item,index)=>({label:`Week ${index+1}`,short:`W${index+1}`,value:Number(item.weight)||0})).filter(item=>item.value);
  target.insertAdjacentHTML('beforeend',`<div class="sec-label">Weekly coaching summary</div><section class="card weekly-summary"><div class="summary-grid"><div><strong>${logs.length}</strong><span>workouts</span></div><div><strong>${displayVolume(volume)}</strong><span>${workoutUnit()} volume</span></div><div><strong>${avgKcal||'—'}</strong><span>avg kcal</span></div><div><strong>${avgProtein||'—'}${avgProtein?'g':''}</strong><span>avg protein</span></div><div><strong>${Math.round(habitDone/habitTotal*100)}%</strong><span>habits</span></div><div><strong>${weightChange===null?'—':`${weightChange>0?'+':''}${weightChange.toFixed(1)}`}</strong><span>weight change</span></div></div><div class="coach-note">${logs.length>=3?'Training consistency is strong. Use the Gym recommendations to progress one variable at a time.':logs.length?'Good start. Aim for at least three quality sessions this week.':'Log your first workout to unlock personalized progression guidance.'}</div></section><div class="sec-label">Trends</div><div class="insight-grid"><section class="card"><div class="insight-title">Training volume · 7 days (${workoutUnit()})</div>${barChart(volumeByDate,'#7c5cfc')}</section><section class="card"><div class="insight-title">Calories · 7 days</div>${barChart(calorieBars,C().a)}</section><section class="card"><div class="insight-title">Body weight</div>${weightBars.length?barChart(weightBars,C().t,value=>`${Number(value).toFixed(0)}`):'<div class="empty">Add weekly weight entries to see this chart.</div>'}</section><section class="card"><div class="insight-title">Personal records</div>${records.length?records.slice(0,5).map(([name,record])=>`<div class="pr-row"><span>${h(name)}</span><strong>${weightText(record.weight)} × ${record.reps}</strong></div>`).join(''):'<div class="empty">Complete weighted sets to establish your records.</div>'}</section></div>`);
}
