const progressRatingHTML=(label,key,value,color,week)=>`<div class="rating-group"><div class="rating-label">${label}</div><div class="rating-buttons">${[1,2,3,4,5].map(score=>`<button class="rating-control" aria-label="${label} ${score}" aria-pressed="${value==score}" onclick="S.progress[${week}].${key}='${score}';save();rProg()" style="border-color:${value==score?color:'var(--border)'};background:${value==score?`${color}18`:'var(--bg3)'};color:${value==score?color:'var(--text3)'}">${score}</button>`).join('')}</div></div>`;
const progressMeasurementUnit=key=>profileUnit()==='metric'?(key==='weight'?'kg':'cm'):(key==='weight'?'lb':'in');
const progressMeasurementValue=(key,value)=>{if(value===''||value==null)return'';const number=Number(value);if(!Number.isFinite(number))return'';const converted=profileUnit()==='metric'?(key==='weight'?number*.453592:number*2.54):number;return Math.round(converted*10)/10};
function updateProgressMeasurement(index,key,input,commit=false){const metric=profileUnit()==='metric',limits=key==='weight'?(metric?[23,680]:[50,1500]):(metric?[25,508]:[10,200]),number=input.value===''?null:Number(input.value),valid=number===null||Number.isFinite(number)&&number>=limits[0]&&number<=limits[1];if(!valid){input.setAttribute('aria-invalid','true');if(commit){S.progress[index][key]='';input.value='';save();toast(`Enter a value from ${limits[0]} to ${limits[1]}.`)}return false}input.removeAttribute('aria-invalid');const stored=number===null?'':metric?(key==='weight'?number/.453592:number/2.54):number;S.progress[index][key]=stored===''?'':String(Math.round(stored*100)/100);save();return true}
function rProg(){
  const c=C(),wi=S.activeProgressWeek,p=S.progress[wi],weights=S.progress.map(item=>parseFloat(item.weight)).filter(Number.isFinite),displayWeights=weights.map(value=>progressMeasurementValue('weight',value)),change=displayWeights.length>1?(displayWeights.at(-1)-displayWeights[0]).toFixed(1):null,weightUnit=progressMeasurementUnit('weight'),waistUnit=progressMeasurementUnit('waist'),metric=profileUnit()==='metric';
  document.getElementById('page-progress').innerHTML=`${pageIntroHTML('PROGRESS // 03','Progress','Log the signal. Adjust with confidence.')}<div class="sec-label">Select week</div><div class="week-sel">${S.progress.map((_,index)=>`<button class="wpill ${wi===index?'active':''}" aria-pressed="${wi===index}" onclick="S.activeProgressWeek=${index};save();rProg()">Week ${index+1}</button>`).join('')}</div><section class="card ca-blue"><div class="progress-inputs"><label>Weight (${weightUnit})<input aria-label="Weekly weight" type="number" min="${metric?23:50}" max="${metric?680:1500}" inputmode="decimal" value="${progressMeasurementValue('weight',p.weight)}" placeholder="0" oninput="updateProgressMeasurement(${wi},'weight',this)" onchange="updateProgressMeasurement(${wi},'weight',this,true)"></label><label>Waist (${waistUnit})<input aria-label="Weekly waist" type="number" min="${metric?25:10}" max="${metric?508:200}" inputmode="decimal" value="${progressMeasurementValue('waist',p.waist)}" placeholder="—" oninput="updateProgressMeasurement(${wi},'waist',this)" onchange="updateProgressMeasurement(${wi},'waist',this,true)"></label></div><div class="progress-ratings">${progressRatingHTML('Energy','energy',p.energy,c.a,wi)}${progressRatingHTML('Strength','strength',p.strength,c.b,wi)}</div><label class="progress-notes">Notes<textarea aria-label="Weekly notes" maxlength="2000" placeholder="How did you feel this week?" oninput="S.progress[${wi}].notes=this.value;save()">${h(p.notes)}</textarea></label></section><div class="sec-label">8-week summary</div><section class="card">${change!==null?`<div class="prog-summary"><div class="psi"><div class="psv" style="color:${parseFloat(change)<0?c.t:c.a}">${parseFloat(change)<0?'':'+'}${change} ${weightUnit}</div><div class="psl">Total change</div></div><div class="psi"><div class="psv" style="color:${c.b}">${displayWeights[0]} ${weightUnit}</div><div class="psl">Start weight</div></div><div class="psi"><div class="psv" style="color:${c.t}">${displayWeights.at(-1)} ${weightUnit}</div><div class="psl">Current weight</div></div></div>`:'<div class="empty">Enter your weight week by week to reveal your trend.</div>'}<div class="progress-history">${S.progress.map((item,index)=>`<button aria-label="Open week ${index+1}" onclick="S.activeProgressWeek=${index};save();rProg()" class="${wi===index?'active':''}"><b>W${index+1}</b><span>${progressMeasurementValue('weight',item.weight)||'—'} ${weightUnit}</span><span>${progressMeasurementValue('waist',item.waist)||'—'} ${waistUnit}</span><span>${item.energy?'★'.repeat(Number(item.energy)):'—'}</span></button>`).join('')}</div></section>`;
  if(typeof renderInsights==='function')renderInsights('page-progress');
}
function rHabits(){
  const c=C(),totals=S.habitNames.map((_,habitIndex)=>DS.reduce((sum,_,dayIndex)=>sum+(S.habits[`h${habitIndex}_d${dayIndex}`]?1:0),0)),done=totals.reduce((sum,value)=>sum+value,0),max=S.habitNames.length*7;
  document.getElementById('page-habits').innerHTML=`${pageIntroHTML('HABITS // 04','Habits','Small promises, kept every day.')}<section class="habit-overview"><div><span>Completed</span><strong>${done}<small> / ${max}</small></strong></div><div><span>Rate</span><strong>${Math.round(done/max*100)}%</strong></div><div><span>Best</span><strong>${Math.max(...totals,0)}<small> / 7</small></strong></div></section><div class="sec-label">Daily habits</div><section class="card ca-blue">${S.habitNames.map((name,habitIndex)=>`<div class="habit-row"><div class="habit-row-top"><div class="habit-name">${h(name)}</div><div class="hscore" style="color:${totals[habitIndex]>=6?c.t:totals[habitIndex]>=4?c.a:'var(--text3)'}">${totals[habitIndex]}/7</div></div><div class="habit-days">${DS.map((day,dayIndex)=>{const key=`h${habitIndex}_d${dayIndex}`,checked=Boolean(S.habits[key]);return`<button class="hdb ${checked?'active':''}" aria-label="${h(name)}, ${day}" aria-pressed="${checked}" onclick="S.habits['${key}']=!S.habits['${key}'];save();rHabits();toast(S.habits['${key}']?'Habit completed':'Habit unchecked')">${day}</button>`}).join('')}</div></div>`).join('')}</section><div class="sec-label">Habit progress</div><section class="card">${S.habitNames.map((name,index)=>{const percent=Math.round(totals[index]/7*100),color=totals[index]>=6?c.t:totals[index]>=4?c.a:c.r;return`<div class="bar-row"><div class="bar-lbl" style="width:100px">${h(name.split(' ').slice(0,2).join(' '))}</div><div class="bar-bg"><div class="bar-fill" style="width:${percent}%;background:${color}"></div></div><div class="bar-num" style="color:${color}">${percent}%</div></div>`}).join('')}</section>`;
}
