const BM_PIN_KEY='bm_device_pin';
let pinAttempts=0,pinCooldownUntil=0;
function pinConfig(){try{const config=JSON.parse(localStorage.getItem(BM_PIN_KEY));return config?.salt&&config?.hash?config:null}catch(error){return null}}
const bytesHex=bytes=>[...bytes].map(byte=>byte.toString(16).padStart(2,'0')).join('');
async function pinDigest(pin,salt){const data=new TextEncoder().encode(`${salt}:${pin}`),digest=await crypto.subtle.digest('SHA-256',data);return bytesHex(new Uint8Array(digest))}
function securitySettingsHTML(){const enabled=Boolean(pinConfig());return`<div class="setting-row"><div><strong>Device PIN</strong><div>${enabled?'Screen lock enabled on this device':'Optional protection for casual access'}</div></div><div class="setting-actions">${enabled?'<button onclick="showPinLock()">Lock now</button><button onclick="openPinSetup()">Change</button><button class="danger-link" onclick="openDisablePinModal()">Disable</button>':'<button class="primary-mini" onclick="openPinSetup()">Enable PIN</button>'}</div></div><div class="setting-note">The PIN locks the app screen on this device. It does not encrypt browser storage or exported backups.</div>`}
function openPinSetup(){
  const existing=pinConfig();document.getElementById('pin-setup-modal')?.remove();const modal=document.createElement('div');modal.id='pin-setup-modal';modal.className='modal-overlay';modal.onclick=event=>{if(event.target===modal)modal.remove()};modal.innerHTML=`<div class="modal-sheet"><div class="modal-handle"></div><div class="modal-title">${existing?'Change':'Enable'} device PIN</div><div class="modal-sub">Use 4–8 digits. This setting stays only on this device.</div>${existing?'<input class="scan-field" id="pin-current" aria-label="Current PIN" type="password" inputmode="numeric" maxlength="8" placeholder="Current PIN">':''}<input class="scan-field" id="pin-new" aria-label="New PIN" type="password" inputmode="numeric" maxlength="8" placeholder="New PIN"><input class="scan-field" id="pin-confirm" aria-label="Confirm PIN" type="password" inputmode="numeric" maxlength="8" placeholder="Confirm PIN"><button class="scan-btn" onclick="savePinSettings()">Save PIN</button><button class="scan-btn secondary" onclick="document.getElementById('pin-setup-modal').remove()">Cancel</button></div>`;document.body.appendChild(modal);document.getElementById(existing?'pin-current':'pin-new').focus();
}
async function savePinSettings(){
  const existing=pinConfig(),current=document.getElementById('pin-current')?.value||'',next=document.getElementById('pin-new').value,confirmPin=document.getElementById('pin-confirm').value;
  if(existing&&await pinDigest(current,existing.salt)!==existing.hash){toast('Current PIN is incorrect');return}
  if(!/^\d{4,8}$/.test(next)){toast('PIN must contain 4–8 digits');return}if(next!==confirmPin){toast('PIN confirmation does not match');return}
  const salt=bytesHex(crypto.getRandomValues(new Uint8Array(16))),hash=await pinDigest(next,salt);localStorage.setItem(BM_PIN_KEY,JSON.stringify({salt,hash,createdAt:new Date().toISOString()}));document.getElementById('pin-setup-modal')?.remove();rBMI();toast('Device PIN enabled ✓');
}
function openDisablePinModal(){const modal=document.createElement('div');modal.id='pin-disable-modal';modal.className='modal-overlay';modal.innerHTML=`<div class="modal-sheet"><div class="modal-handle"></div><div class="modal-title">Disable device PIN</div><input class="scan-field" id="pin-disable" aria-label="Current PIN" type="password" inputmode="numeric" maxlength="8" placeholder="Current PIN"><button class="scan-btn" onclick="disablePin()">Disable PIN</button><button class="scan-btn secondary" onclick="document.getElementById('pin-disable-modal').remove()">Cancel</button></div>`;document.body.appendChild(modal);document.getElementById('pin-disable').focus()}
async function disablePin(){const config=pinConfig(),pin=document.getElementById('pin-disable').value;if(!config||await pinDigest(pin,config.salt)!==config.hash){toast('Current PIN is incorrect');return}localStorage.removeItem(BM_PIN_KEY);document.getElementById('pin-disable-modal')?.remove();rBMI();toast('Device PIN disabled')}
function showPinLock(){
  if(!pinConfig())return;document.getElementById('pin-lock')?.remove();const lock=document.createElement('div');lock.id='pin-lock';lock.className='pin-lock';lock.innerHTML=`<div class="pin-card"><div class="pin-brand">BEAST<span>MODE</span></div><div class="pin-title">App locked</div><div class="pin-sub">Enter your device PIN to continue</div><input id="pin-unlock" aria-label="Unlock PIN" type="password" inputmode="numeric" maxlength="8" autocomplete="off" onkeydown="if(event.key==='Enter')unlockApp()"><button onclick="unlockApp()">Unlock</button><div id="pin-message" role="alert"></div></div>`;document.body.appendChild(lock);document.getElementById('pin-unlock').focus();
}
async function unlockApp(){
  const now=Date.now(),message=document.getElementById('pin-message');if(now<pinCooldownUntil){message.textContent=`Try again in ${Math.ceil((pinCooldownUntil-now)/1000)} seconds`;return}
  const config=pinConfig(),input=document.getElementById('pin-unlock'),valid=config&&await pinDigest(input.value,config.salt)===config.hash;if(valid){pinAttempts=0;document.getElementById('pin-lock')?.remove();return}
  pinAttempts++;input.value='';if(pinAttempts>=5){pinCooldownUntil=Date.now()+30000;pinAttempts=0;message.textContent='Too many attempts. Try again in 30 seconds.'}else message.textContent=`Incorrect PIN · ${5-pinAttempts} attempts remaining`;
}
function initAppSecurity(){if(pinConfig())showPinLock()}
